### PR TITLE
Edit TE Activity: Bypass intent.Extras

### PR DESCRIPTION
**Pull request by masterrr**
Closing https://github.com/toggl/mobile/issues/772
http://stackoverflow.com/a/18154106/1279330

### CODE REVIEW

**Comment by monday8am** [comment]
the new code is better because there is a null check in the original call to getStringArrayListExtra
```
  public ArrayList<String> getStringArrayListExtra(String name) {
        return mExtras == null ? null : mExtras.getStringArrayList(name);
   }
```

but the issue is still open.  This is the reason of the trick's author: "i'm sure i've had the same issue and the answer i gave you did the trick and never heard of it again..." . Not enough for us.

**Comment by masterrr** [comment]
@monday8am can I put “planned” tag on the issue and see if the bug persist after the update via Bugsnag?

**Comment by monday8am** [comment]
@masterrr "planned" is another concept I think, more related with future improvements. Use "pending" tag ( I didn't created it, was you?) I have defined the same color as XI background :P

**Comment by masterrr** [comment]
@monday8am “pending” is :+1: (yep, I created it :P)

**Pull request merged**
