### PR TITLE
Swipe delete implementation.

### LINKED ISSUE #540: Display delete button on list item swipe.
Epic #443

### PR DESCRIPTION
**Pull request by taavirehemagi**
Closes #540

### CODE REVIEW

**Comment by monday8am** [comment]
- the general solution is ok in the first test ( a listener, a base item, scroll events)
- the animation will need a review but is ok. 
- needs to be rebase with last changes in android-redesign branch.
- but, the event OnDismiss is not connected with the code! (is never called) :) ..

**Comment by taavirehemagi** [comment]
Rebased from android-redesign. I planned the OnDismiss to be used once the RecyclerView for home screen is ready to have some place to attach it to. If I attach it to current adapter, it will be changed anyway, no?

**Comment by monday8am** [comment]
The touch listener will be almost the same. You only need to detect the end of the movement here:
https://github.com/toggl/mobile/blob/taavirehemagi-redesign-swipedismiss/Joey/UI/Utils/SwipeDeleteTouchListener.cs#L87

...and dispatch the OnDismiss event. The animation code is encapsulated in the ListItemSwipeable, try to find a way to notify from the item to the touch listener or move the animation code to the touch listener (like the original code :D)

**Comment by taavirehemagi** [comment]
So you don't mean that I should make the button actually delete data, but just to have the OnDismiss dispatching the end of event? Of course, I will add the OnDismiss to dispatch at end of the animation, (I somehow missed that before). Do you need me to add the actual data deletion as well?

**Comment by monday8am** [comment]
This is the chain of actions:
- Received OnDismiss.
- Get correct TimeEntryModel from RecyclerView using the position received and delete it from list (not from database).
- Show the Undo bar for 3 seconds.
- In case of press Undo, insert the element in same position.
- Hide the Undo bar.
- Try to Delete the TimeEntry from database.

You're in charge of the Undo bar but but just to show / hide it. I'll take care of the rest of actions. The last action is ready from previous code.

**Comment by taavirehemagi** [comment]
got it

**Comment by taavirehemagi** [comment]
Added undo support. Check it out

**Comment by monday8am** [comment]
superseded by #608!

**Pull request closed without merging**
