### PR TITLE
New login screen design implementation

### LINKED ISSUE #678: Login and signup material design placement
toggl-android-signup

### PR DESCRIPTION
**Pull request by taavirehemagi**
Closes #678 #679 #680 #681 #719

### CODE REVIEW

**Comment by monday8am** [comment]
@taavirehemagi  ..ehmm.. 
- the Google button is missing.
- margins are not correct (laterals should be 32dp @pe0ny)
- I'm not sure but the bg photo looks a bit deformed?

nexus 4 kitkat screentshot 3

**Comment by taavirehemagi** [comment]
@monday8am  The google login only appears when there's accounts linked to google on the phone (just like the old version). But I agree, now looking at it, the legal text should be more at the bottom when it's missing. I'll check the bg deformation and the paddings, though.

**Comment by taavirehemagi** [comment]
It appears that on android, backgrounds always stretch to match the container. For me, the screen was right enough size not to notice it before. Did a hack that's supposed to un-stretch the image, though. Can you validate, that it works for you, @monday8am? In addition, I fixed the margins as well.

**Comment by monday8am** [comment]
in case of background, user a bitmap drawable as a background, then you can define image behaviour with the gravity attribute:
https://github.com/toggl/mobile/blob/android-redesign/Joey/Resources/drawable/BgArrowsPattern.xml
http://developer.android.com/reference/android/graphics/drawable/BitmapDrawable.html

**Comment by monday8am** [comment]
wow, you did it :D , I'll check :+1:

**Pull request closed without merging**
