### PR TITLE
Joey edit TE screen redesign

### PR DESCRIPTION
**Pull request by masterrr**
Related
https://github.com/toggl/mobile/issues/511 https://github.com/toggl/mobile/issues/512 https://github.com/toggl/mobile/issues/513 https://github.com/toggl/mobile/issues/514 https://github.com/toggl/mobile/issues/515 https://github.com/toggl/mobile/issues/516

Epic
https://github.com/toggl/mobile/issues/443

### CODE REVIEW

**Comment by taavirehemagi** [comment]
screen shot 2015-02-25 at 15 52 36
The margins and paddings for the Project and Task edit text seem a bit off. (Left one is the mockup)

**Comment by taavirehemagi** [comment]
Also, some times task and project selections don't pop open on click.

**Comment by masterrr** [comment]
@taavirehemagi it will be fixed later (https://github.com/toggl/mobile/issues/525)

**Comment by taavirehemagi** [comment]
ok :+1:

**Comment by masterrr** [comment]
Adjust the layout a bit, also inserted some code so we can open TE Edit on the log fragment just by clicking on entries. Layout looks like this now:
screenshot_2015-02-26-00-16-32

**Comment by masterrr** [comment]
updated look
screenshot_2015-02-26-00-40-25

**Pull request merged**
