### PR TITLE
New login screen design implementation

### LINKED ISSUE #678: Login and signup material design placement
toggl-android-signup

### PR DESCRIPTION
**Pull request by taavirehemagi**
Closes #678 #679 #680 #681 #719

### CODE REVIEW

**Comment by monday8am** [comment]
@taavirehemagi almost completed.
two minor details:
- If I press "Log in" and "Sign up" the button changes the color.
- If you select a TextView to enter the email, the screen "go up" too much and the textview is almost at to of the screen. This happen if the Google button and disclaimers are showed (test on device)

**Comment by taavirehemagi** [comment]
It should change color, because the sign up button is disabled by default and only comes active when the users email is set and a 6 letter password. When it comes active, it's the same color.

**Comment by monday8am** [comment]
>It should change color, because the sign up button is disabled by default and only comes active when the users email is set and a 6 letter password. When it comes active, it's the same color.

Understood, but the behaviour then is different to login page (is red in login page). I checked old version and is like now, go for the other detail then.

**Comment by taavirehemagi** [comment]
@monday8am bump

**Comment by monday8am** [comment]
@taavirehemagi remove the scroll.. naaahh :)

I have move it only to the logo position:

nexus 4 kitkat screentshot 12

**Comment by taavirehemagi** [comment]
is good :+1: Let's merge already :smile:

**Pull request merged**
