### PR TITLE
Added more time to UndoBar. Scroll threshold increased.

### LINKED ISSUE #766: Delay Undo bar time until 6 secons

### PR DESCRIPTION
**Pull request by monday8am**
Some small adjustment to Undo bar. Closes #766 #765

### CODE REVIEW

**Comment by taavirehemagi** [comment]
:+1:

**Comment by masterrr** [comment]
Console.WriteLine into master?

**Comment by monday8am** [comment]
Ups. #btw, are you doing a rhetoric question? :P

**Comment by masterrr** [comment]
A bit :smile:

**Pull request merged**
