### PR TITLE
Client list modifications.

### PR DESCRIPTION
**Pull request by monday8am**
@taavirehemagi Please, rebase your branch with master before check this PR and you'll see the modifications correctly. There are only the 5 or 6 last commits. 

After some refactoring, the only problem is the blue area that you'll see if you test my solution. We need to wrap the content inside the Alert Dialog.

### CODE REVIEW

**Comment by taavirehemagi** [comment]
My branch is now up to date with master. I'm not sure why it doesn't show it correctly

**Comment by monday8am** [comment]
did you forced a push?

**Comment by taavirehemagi** [comment]
yes I did. why?

**Comment by taavirehemagi** [comment]
Superseded by #961

**Pull request closed without merging**
