### PR TITLE
Splash screen implementation.

### LINKED ISSUE #640: Set a new Splash view
Splash view isn't showed.

### PR DESCRIPTION
**Pull request by taavirehemagi**
Closes #640

### CODE REVIEW

**Comment by monday8am** [comment]
@taavirehemagi :+1: 
Just a question, do you know why we didn't have splash screen before? Probably there is a reason :)

**Comment by taavirehemagi** [comment]
I'm not sure if there is a reason. This is the suggested way of doing it and I can see no reason why not to do it. Maybe it wasn't considered necessary before?

http://developer.xamarin.com/guides/android/user_interface/creating_a_splash_screen/

**Comment by monday8am** [comment]
@taavirehemagi "splashdrawable" file is missing.

**Comment by taavirehemagi** [comment]
rready to use

**Pull request merged**
